<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Lesaja</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
    <div class="align-navbar align-items-center">
        <nav class="navbar navbar-expand-md bg-light navbar- sticky-top">
        <!-- Brand -->
        <a class="navbar-brand">
            <img src="img/lesaja.png" width=120>
        </a>

        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link" href="/kelas">Kelas Saya</a>
            </li>
                <input class="search-bar mr-sm-2" type="text" placeholder="Kelas apa yang kamu ingin ikuti hari ini?" width=100>
                    <button class="btn search-btn" type="submit">
                        <img src="img/search.png" width=20>
                    </button>
                    <label class="nama" for="nama_murid"><?php echo $this->session->get('AUTH_NAME'); ?></label>
                    <button class="btn dropdwon-toggle" id="nama_murid" data-toggle="dropdown">
                        <img src="img/user.png">
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="/edit_profil">Edit Profile</a>
                        <a class="dropdown-item" href="/">Keluar</a>
                    </div>
            </form>
        </nav>
    </div>

    <!-- content -->
    <div class="">
        <div>

        </div>
    </div>
    
</body>
</html>