<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Reset Password</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
<?php echo $this->tag->form("reset-password"); ?> 
    <div class="box" align = "center"> 
        <div class="content" align="center">
            <p>
            <?php echo Phalcon\Tag::linkTo('dashboard','<img src="img/lesaja.png" width=250>');?>
            </p>
            <h5><br>
            <label class="text-reset" for="reset">Reset Password</label>
            </h5>
            <p><br>
            <input class="form-control mr-sm-2" type="password" placeholder="Masukkan Password Lama">
            </p>
            <p><br>
            <input class="form-control mr-sm-2" type="password" placeholder="Masukkan Password Baru">
            </p>
            <p><br>
            <input class="form-control mr-sm-2" type="password" placeholder="Konfirmasi Password Baru">
            </p><br>
            <div align="center">
                <button class="btn btn-outline-small btn-primary:hover" type="button">CANCEL</button>
                <button class="btn btn-submit btn-primary:hover" type="button">SUBMIT</button>
            </div>
       </div>   
    </div> 
</form>
</body>
</html>