<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
<?php echo $this->tag->form("dashboard"); ?> 
    <div class="box" align = "center"> 
        <div class="content" align="center">
            <p>
            <?php echo Phalcon\Tag::linkTo('dashboard','<img src="img/lesaja.png" width=300>');?>
            </p>
            <br>
            <p><br>
            <input class="form-control mr-sm-2" type="text" placeholder="Email">
                <!-- <php echo $this->tag->textField("Email"); ?> -->
            </p>
            <p><br>
            <input class="form-control mr-sm-2" type="password" placeholder="Password">
                <!-- <php echo $this->tag->textField("Password"); ?>   -->
            </p>  
            <h6 align="right">
                <a href="reset" class="btn btn-link">Lupa Password?</a>
            </h6>
            <button class="btn btn-login-register btn-primary:hover" type="button">MASUK</button>
            <br>
            <br>
            <div class="bottom-login" align="center">
                <label class="register" for="register-info">Belum punya akun?</label>
                <button class="btn btn-outline-medium" type="button">Daftar Sekarang</button>
            </div>
       </div>     
    </div> 
</form>
</body> 
</body>
</html>